// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BC2LRw-PURRNjrEMyvO1O3h3WkVf7g8',
    appId: '1:910622737109:web:f72418e7b8f7e39917585c',
    messagingSenderId: '910622737109',
    projectId: 'boardpc-c7a68',
    authDomain: 'boardpc-c7a68.firebaseapp.com',
    storageBucket: 'boardpc-c7a68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2LHl47qZAAUy228boOesj_DO3ftyhEM',
    appId: '1:910622737109:android:a30e3fc31f48b64b17585c',
    messagingSenderId: '910622737109',
    projectId: 'boardpc-c7a68',
    storageBucket: 'boardpc-c7a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Im1YwQClHtws0jHzsEB2OegRL9KSDV0',
    appId: '1:910622737109:ios:d34db5efa4f2d99217585c',
    messagingSenderId: '910622737109',
    projectId: 'boardpc-c7a68',
    storageBucket: 'boardpc-c7a68.appspot.com',
    iosClientId: '910622737109-fq58vn2jbokuav6jm2rhrsd3b3ikkfkc.apps.googleusercontent.com',
    iosBundleId: 'com.iet.prof.event',
  );
}
